git:
  depth: false
  quiet: true

language: cpp

jobs:
  include:

    #
    # linux (g++)
    #

    - os: linux
      dist: xenial
      stage: linux
      name: g++-4.9
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["g++-4.9"] } }
      env: CC=gcc-4.9 CXX=g++-4.9
      script: .ci/build_linux.sh

    - os: linux
      dist: xenial
      stage: linux
      name: g++-5
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["g++-5"] } }
      env: CC=gcc-5 CXX=g++-5
      script: .ci/build_linux.sh

    #
    # linux (clang++)
    #

    - os: linux
      dist: xenial
      stage: linux
      name: clang++-3.8
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["clang-3.8"] } }
      env: CC=clang-3.8 CXX=clang++-3.8
      script: .ci/build_linux.sh

    - os: linux
      dist: xenial
      stage: linux
      name: clang++-4.0
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["clang-4.0"] } }
      env: CC=clang-4.0 CXX=clang++-4.0
      script: .ci/build_linux.sh

    #
    # darwin
    #

    - os: osx
      osx_image: xcode10
      stage: darwin
      name: xcode10
      script: .ci/build_darwin.sh

    - os: osx
      osx_image: xcode11
      stage: darwin
      name: xcode11
      script: .ci/build_darwin.sh

    #
    # coverage
    #

    - os: osx
      osx_image: xcode10
      stage: coverage
      name: coverage
      addons: { homebrew: { packages: ["lcov"], update: true } }
      script: .ci/build_coverage.sh
